<?php

declare(strict_types=1);

require_once __DIR__ . '/../repository/UserRepository.php';
require_once __DIR__ . '/../repository/RatingRepository.php';
require_once __DIR__ . '/../repository/BidRepository.php'; // Required for "My Bids" tab
require_once __DIR__ . '/../model/Rating.php';

class UserService
{
    private UserRepository $userRepo;
    private RatingRepository $ratingRepo;
    private BidRepository $bidRepo;

    public function __construct(
        UserRepository $userRepo,
        RatingRepository $ratingRepo,
        BidRepository $bidRepo
    ) {
        $this->userRepo = $userRepo;
        $this->ratingRepo = $ratingRepo;
        $this->bidRepo = $bidRepo;
    }

    /**
     * Requirement A.2.3: Edit Profile (Name)
     */
    public function updateProfileName(int $userId, string $firstName, string $lastName): void
    {
        if (empty(trim($firstName)) || empty(trim($lastName))) {
            throw new Exception("First name and last name cannot be empty.");
        }

        $this->userRepo->updateName($userId, trim($firstName), trim($lastName));
    }

    /**
     * Requirement A.2.2: Fetch User Profile Data (Header Info)
     */
    public function getProfileInfo(int $userId): ?User
    {
        $user = $this->userRepo->getUserById($userId);
        if (!$user) {
            throw new Exception("User not found.");
        }
        return $user;
    }

    /**
     * Requirement A.2.2: Profile Tabs - "My Ratings" (Received)
     */
    public function getReceivedRatings(int $userId): array
    {
        return $this->ratingRepo->getReceivedRatings($userId);
    }

    /**
     * Requirement A.2.2: Profile Tabs - "Given Ratings"
     */
    public function getGivenRatings(int $userId): array
    {
        return $this->ratingRepo->getGivenRatings($userId);
    }

    /**
     * Requirement A.2.2: Profile Tabs - "Bid History"
     * NOTE: Requires BidRepository to implement `getBidsByUserId($id)`
     */
    public function getUserBidHistory(int $userId): array
    {
        return $this->bidRepo->getPastBidsByUserId($userId);
    }

    /**
     * Requirement A.2.12: Rate a transaction partner.
     * Logic: Adds rating AND updates the user's average score immediately.
     */
    public function submitRating(int $raterId, int $rateeId, int $itemId, int $stars, string $comment): void
    {
        // 1. Validation
        if ($stars < 1 || $stars > 5) {
            throw new Exception("Rating must be between 1 and 5 stars.");
        }

        if ($raterId === $rateeId) {
            throw new Exception("You cannot rate yourself.");
        }

        // Optional: Check if transaction exists and is completed?
        // Usually handled by UI context, but could be validated via ItemRepo here.

        // 2. Create Rating Object
        $rating = new Rating(
            null, // ID generated by DB
            $itemId,
            $raterId,
            $rateeId,
            $stars,
            $comment,
            new DateTimeImmutable()
        );

        // 3. Save Rating
        $this->ratingRepo->addRating($rating);

        // 4. Update the User's Average Score (Requirement A.2.12)
        // This ensures the profile shows the new average immediately without recalculating on every view.
        $this->userRepo->updateAverageRating($rateeId);
    }
}